name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  mongo_dart: ^0.10.8
  http: ^1.2.2
  archive: ^4.0.9
  xml: ^6.5.0
  mailer: ^6.1.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
